### ISSUE TITLE
logname: no login name

### ISSUE THREAD

**Issue by alinbandiu198** [n3oxmind/gns3theme#7]
Hi , when i try to install the theme I got this error logname: no login name even if i run it as root.

**Comment by n3oxmind** [comment]
@alinbandiu198 , What system are you running ?

**Comment by alinbandiu198** [comment]
I am using Ubuntu Budgie  [
![issuee](https://user-images.githubusercontent.com/63589818/101012536-a622bf80-356b-11eb-99a8-f65ce7eb9830.png)

**Comment by n3oxmind** [comment]
I pushed an update to the master. Please give it a try and let me know.
https://github.com/n3oxmind/gns3theme/archive/master.zip

use the same command that you used before:
`sudo ./gns3theme.sh --install --src /home/alin/Downloads/gns3-gui-2.2.16`

if the above command did not work. Please add -u user to make it work  (I added this recently).
`sudo ./gns3theme.sh --install --src /home/alin/Downloads/gns3-gui-2.2.16 -u alin`

**Comment by alinbandiu198** [comment]
@n3oxmind  
I have tried , unlucky i got the same error

**Comment by n3oxmind** [comment]
@alinbandiu198 ,
It looks like `logname` command does not work correctly on your system (google the error for more details if you're interested).

I removed  `logname` dependency. Please give it another try using this command.

`sudo ./gns3theme.sh --install --src /home/alin/Downloads/gns3-gui-2.2.16 -u alin`


make sure to download the most updated version 
https://github.com/n3oxmind/gns3theme/archive/master.zip

**Comment by alinbandiu198** [comment]
thanks , the command worked now ,i also installed a scheme but under the interface style i can't select custom it still shows the defaults 
![Uploading here.png…]()

**Comment by n3oxmind** [comment]
@alinbandiu198 ,
That's because I forgot to update the username in style.py. I fixed that and tested it with the latest release of gns3-gui (2.2.17).

-Have fun

**Comment by alinbandiu198** [comment]
It Works !!! Thank you
